#!/bin/sh

rm -rf .rev \
&& rm -rf .publish_stage \
&& mkdir .publish_stage \
&& gulp build \
&& cd .publish_stage \
&& git init \
&& git checkout -b gh-pages \
&& git remote add origin https://github.com/blakelapierre/chainit \
&& git pull origin gh-pages \
&& git rm -r . \
&& echo "chan.best" > CNAME \
&& cp  -r ../.rev/* . \
&& git add . \
&& git commit -m ".rev" \
&& git push origin gh-pages
